CSP and timezone config update
onaio/ansible-onadata pull request #49
Opened 2023-01-13 13:58 UTC by FrankApiyo

2023-01-13 14:00 UTC, DavisRayM approved these changes

2023-03-01 05:37 UTC, KipSigei approved these changes

2023-03-01 05:58 UTC, ciremusyoka submitted a review, later dismissed

2023-04-04 07:45 UTC, KipSigei submitted a review, later dismissed

2023-04-04 07:50 UTC, KipSigei requested changes

2023-04-04 07:50 UTC, KipSigei commented on defaults/main.yml
>  onadata_celeryd_nodes: "{{ onadata_domain }} export-node publish-xls-form-node google-export xls-exports csv-exports kml-exports osm-exports csv-zip-exports sav-zip-exports external-exports zip-expor
could we update the `xls-exports` queue to `xlsx-exports` for context purposes?

2023-04-04 07:52 UTC, KipSigei requested changes

2023-04-04 07:52 UTC, KipSigei commented on defaults/main.yml
>    xls_exports:
update to `xlsx_exports`

2023-04-04 07:57 UTC, KipSigei approved these changes

2023-04-04 08:06 UTC, merged